services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    hostname: db
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=true
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT getdate()" -b
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
